AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 50
    MemorySize: 5000
  Api:
    BinaryMediaTypes:
    - image/png
    - image/jpg
    - image/jpeg
Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        Inference:
          Type: Api
          Properties:
            Path: /classify_digit
            Method: post
      ImageUri: inferencefunction:python3.9-v1
    Metadata:
      DockerContext: /home/devel/wc/kalixta/repositories/fashion-classification/fashion-classifier/app
      DockerTag: python3.9-v1
      Dockerfile: Dockerfile
      SamResourceId: InferenceFunction
Outputs:
  InferenceApi:
    Description: API Gateway endpoint URL for Prod stage for Inference function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/classify_digit/
  InferenceFunction:
    Description: Inference Lambda Function ARN
    Value:
      Fn::GetAtt:
      - InferenceFunction
      - Arn
  InferenceFunctionIamRole:
    Description: Implicit IAM Role created for Inference function
    Value:
      Fn::GetAtt:
      - InferenceFunctionRole
      - Arn
